server:
  servlet:
    context-path: /hotel
  port: 8081

spring:
  application:
    name: BOOKING-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/upgrad
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka